export const navigations = [
    {
        id: 1,
        parentId: 0,
        label: 'Vue',
        data: 'vue',
        icon: '/icons/vue.png',
    },
    {
        id: 1,
        parentId: 0,
        label: 'English',
        data: 'english',
        icon: '/icons/english.png',
    },
    {
        id: 2,
        parentId: 0,
        label: 'Angular',
        data: 'angular',
        icon: '/icons/angular.png',
    },
    {
        id: 3,
        parentId: 0,
        label: 'React',
        data: 'react',
        icon: '/icons/react.png',
    },
    {
        id: 4,
        parentId: 0,
        label: 'Flutter',
        data: 'flutter',
        icon: '/icons/flutter.png',
    },
    {
        id: 5,
        parentId: 0,
        label: 'JavaScript',
        data: 'JavaScript',
        icon: '/icons/javaScript.png',
    },
    {
        id: 6,
        parentId: 0,
        label: 'Nest',
        data: 'nest',
        icon: '/icons/nest.png',
    },
    {
        id: 7,
        parentId: 0,
        label: 'Nuxt',
        data: 'nuxt',
        icon: '/icons/nuxt.png',
    },
    {
        id: 8,
        parentId: 0,
        label: 'Ionic',
        data: 'ionic',
        icon: '/icons/ionic.png',
    },
    {
        id: 9,
        parentId: 0,
        label: 'Typescript',
        data: 'typescript',
        icon: '/icons/typescript.png',
    },
    {
        id: 10,
        parentId: 0,
        label: 'OOP',
        data: 'oop',
        icon: '/icons/oop.png',
    },
    {
        id: 11,
        parentId: 0,
        label: 'css',
        data: 'css',
        icon: '/icons/css.png',
    },
    {
        id: 12,
        parentId: 0,
        label: 'scss',
        data: 'scss',
        icon: '/icons/scss.png',
    },
]